// migration.js
const connectDB = require('../config/db');
const mongoose = require('mongoose');
const Skills = require('../models/Skills');

const skills = [
  // Programming Languages
  { skill: 'Python', type: 'programming_language' },
  { skill: 'JavaScript', type: 'programming_language' },
  { skill: 'TypeScript', type: 'programming_language' },
  { skill: 'CSharp', type: 'programming_language' },
  { skill: 'CPlusPlus', type: 'programming_language' },
  { skill: 'Java', type: 'programming_language' },
  { skill: 'Golang', type: 'programming_language' },
  { skill: 'Ruby', type: 'programming_language' },
  { skill: 'PHP', type: 'programming_language' },
  { skill: 'Swift', type: 'programming_language' },
  { skill: 'Kotlin', type: 'programming_language' },
  { skill: 'Rust', type: 'programming_language' },
  { skill: 'Scala', type: 'programming_language' },
  { skill: 'R', type: 'programming_language' },
  { skill: 'Dart', type: 'programming_language' },
  { skill: 'Lua', type: 'programming_language' },
  { skill: 'MATLAB', type: 'programming_language' },
  { skill: 'Groovy', type: 'programming_language' },
  { skill: 'Perl', type: 'programming_language' },
  { skill: 'Haskell', type: 'programming_language' },
  { skill: 'Assembly', type: 'programming_language' },
  { skill: 'ObjectiveC', type: 'programming_language' },
  { skill: 'VBA', type: 'programming_language' },

  // Frontend Frameworks/Libraries
  { skill: 'React', type: 'frontend' },
  { skill: 'ReactNative', type: 'frontend' },
  { skill: 'ReactRedux', type: 'frontend' },
  { skill: 'ReactQuery', type: 'frontend' },
  { skill: 'ReactRouter', type: 'frontend' },
  { skill: 'ReactHookForm', type: 'frontend' },
  { skill: 'NextJS', type: 'frontend' },
  { skill: 'Vue', type: 'frontend' },
  { skill: 'VueX', type: 'frontend' },
  { skill: 'VueRouter', type: 'frontend' },
  { skill: 'Nuxt', type: 'frontend' },
  { skill: 'Angular', type: 'frontend' },
  { skill: 'AngularJS', type: 'frontend' },
  { skill: 'Svelte', type: 'frontend' },
  { skill: 'SvelteKit', type: 'frontend' },
  { skill: 'TailwindCSS', type: 'frontend' },
  { skill: 'Bootstrap', type: 'frontend' },
  { skill: 'MaterialUI', type: 'frontend' },
  { skill: 'ChakraUI', type: 'frontend' },
  { skill: 'AntDesign', type: 'frontend' },
  { skill: 'StyledComponents', type: 'frontend' },
  { skill: 'Sass', type: 'frontend' },
  { skill: 'Less', type: 'frontend' },
  { skill: 'WebGL', type: 'frontend' },
  { skill: 'ThreeJS', type: 'frontend' },
  { skill: 'D3JS', type: 'frontend' },
  { skill: 'Gatsby', type: 'frontend' },
  { skill: 'Electron', type: 'frontend' },
  { skill: 'PWA', type: 'frontend' },
  { skill: 'WebAssembly', type: 'frontend' },
  { skill: 'Redux', type: 'frontend' },
  { skill: 'ReduxSaga', type: 'frontend' },
  { skill: 'ReduxThunk', type: 'frontend' },
  { skill: 'MobX', type: 'frontend' },
  { skill: 'GraphQL', type: 'frontend' },
  { skill: 'Apollo', type: 'frontend' },
  { skill: 'WebSockets', type: 'frontend' },

  // Backend Frameworks
  { skill: 'Django', type: 'backend' },
  { skill: 'DjangoREST', type: 'backend' },
  { skill: 'Flask', type: 'backend' },
  { skill: 'FastAPI', type: 'backend' },
  { skill: 'NodeJS', type: 'backend' },
  { skill: 'Express', type: 'backend' },
  { skill: 'NestJS', type: 'backend' },
  { skill: 'SpringBoot', type: 'backend' },
  { skill: 'SpringMVC', type: 'backend' },
  { skill: 'SpringSecurity', type: 'backend' },
  { skill: 'DotNET', type: 'backend' },
  { skill: 'DotNETCore', type: 'backend' },
  { skill: 'Laravel', type: 'backend' },
  { skill: 'Symfony', type: 'backend' },
  { skill: 'RubyOnRails', type: 'backend' },
  { skill: 'Phoenix', type: 'backend' },
  { skill: 'ASPNETCore', type: 'backend' },
  { skill: 'Hibernate', type: 'backend' },
  { skill: 'EntityFramework', type: 'backend' },
  { skill: 'Sequelize', type: 'backend' },
  { skill: 'TypeORM', type: 'backend' },
  { skill: 'Prisma', type: 'backend' },
  { skill: 'GinGonic', type: 'backend' },
  { skill: 'Echo', type: 'backend' },
  { skill: 'Fiber', type: 'backend' },
  { skill: 'AdonisJS', type: 'backend' },
  { skill: 'Strapi', type: 'backend' },

  // Databases
  { skill: 'MongoDB', type: 'database' },
  { skill: 'PostgreSQL', type: 'database' },
  { skill: 'MySQL', type: 'database' },
  { skill: 'Redis', type: 'database' },
  { skill: 'ElasticSearch', type: 'database' },
  { skill: 'SQLite', type: 'database' },
  { skill: 'DynamoDB', type: 'database' },
  { skill: 'Cassandra', type: 'database' },
  { skill: 'MariaDB', type: 'database' },
  { skill: 'OracleDB', type: 'database' },
  { skill: 'CouchDB', type: 'database' },
  { skill: 'Neo4j', type: 'database' },
  { skill: 'Firebase', type: 'database' },
  { skill: 'InfluxDB', type: 'database' },
  { skill: 'Memcached', type: 'database' },
  { skill: 'RethinkDB', type: 'database' },
  { skill: 'Fauna', type: 'database' },
  { skill: 'Supabase', type: 'database' },

  // Cloud Services
  { skill: 'AWS', type: 'cloud' },
  { skill: 'AWSLambda', type: 'cloud' },
  { skill: 'AWSS3', type: 'cloud' },
  { skill: 'AWSCloudfront', type: 'cloud' },
  { skill: 'AWSEC2', type: 'cloud' },
  { skill: 'AWSRDS', type: 'cloud' },
  { skill: 'AWSRoute53', type: 'cloud' },
  { skill: 'AWSEKS', type: 'cloud' },
  { skill: 'GoogleCloud', type: 'cloud' },
  { skill: 'GoogleCloudFunctions', type: 'cloud' },
  { skill: 'GoogleCloudRun', type: 'cloud' },
  { skill: 'Azure', type: 'cloud' },
  { skill: 'AzureFunctions', type: 'cloud' },
  { skill: 'AzureDevOps', type: 'cloud' },
  { skill: 'Heroku', type: 'cloud' },
  { skill: 'DigitalOcean', type: 'cloud' },
  { skill: 'Vercel', type: 'cloud' },
  { skill: 'Netlify', type: 'cloud' },
  { skill: 'CloudFlare', type: 'cloud' },

  // DevOps & Tools
  { skill: 'Docker', type: 'devops' },
  { skill: 'DockerCompose', type: 'devops' },
  { skill: 'Kubernetes', type: 'devops' },
  { skill: 'Jenkins', type: 'devops' },
  { skill: 'GitHubActions', type: 'devops' },
  { skill: 'CircleCI', type: 'devops' },
  { skill: 'TravisCI', type: 'devops' },
  { skill: 'Terraform', type: 'devops' },
  { skill: 'Ansible', type: 'devops' },
  { skill: 'Puppet', type: 'devops' },
  { skill: 'Chef', type: 'devops' },
  { skill: 'Grafana', type: 'devops' },
  { skill: 'Prometheus', type: 'devops' },
  { skill: 'ELK', type: 'devops' },
  { skill: 'Nginx', type: 'devops' },
  { skill: 'Apache', type: 'devops' },
  { skill: 'Git', type: 'devops' },
  { skill: 'GitLab', type: 'devops' },
  { skill: 'Bitbucket', type: 'devops' },
  { skill: 'Jira', type: 'devops' },
  { skill: 'Confluence', type: 'devops' },
  { skill: 'SonarQube', type: 'devops' },
  { skill: 'Helm', type: 'devops' },
  { skill: 'ArgoCD', type: 'devops' },

  // Testing
  { skill: 'Jest', type: 'testing' },
  { skill: 'Mocha', type: 'testing' },
  { skill: 'Chai', type: 'testing' },
  { skill: 'Cypress', type: 'testing' },
  { skill: 'Selenium', type: 'testing' },
  { skill: 'Playwright', type: 'testing' },
  { skill: 'TestingLibrary', type: 'testing' },
  { skill: 'Jasmine', type: 'testing' },
  { skill: 'Karma', type: 'testing' },
  { skill: 'PyTest', type: 'testing' },
  { skill: 'JUnit', type: 'testing' },
  { skill: 'XUnit', type: 'testing' },
  { skill: 'NUnit', type: 'testing' },
  { skill: 'PHPUnit', type: 'testing' },

  // Mobile Development
  { skill: 'Flutter', type: 'mobile' },
  { skill: 'ReactNative', type: 'mobile' },
  { skill: 'Xamarin', type: 'mobile' },
  { skill: 'iOSDevelopment', type: 'mobile' },
  { skill: 'AndroidDevelopment', type: 'mobile' },
  { skill: 'SwiftUI', type: 'mobile' },
  { skill: 'KotlinMultiplatform', type: 'mobile' },
  { skill: 'Capacitor', type: 'mobile' },
  { skill: 'Ionic', type: 'mobile' },
  { skill: 'NativeScript', type: 'mobile' },

  // AI/ML
  { skill: 'TensorFlow', type: 'ai_ml' },
  { skill: 'PyTorch', type: 'ai_ml' },
  { skill: 'Keras', type: 'ai_ml' },
  { skill: 'ScikitLearn', type: 'ai_ml' },
  { skill: 'OpenCV', type: 'ai_ml' },
  { skill: 'Pandas', type: 'ai_ml' },
  { skill: 'NumPy', type: 'ai_ml' },
  { skill: 'ComputerVision', type: 'ai_ml' },
  { skill: 'NLP', type: 'ai_ml' },
  { skill: 'MachineLearning', type: 'ai_ml' },
  { skill: 'DeepLearning', type: 'ai_ml' },
];

async function seedSkills() {
  try {
    await connectDB();

    await Skills.deleteMany({});
    await Skills.insertMany(skills);

    console.log('Skills seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding skills:', error);
    process.exit(1);
  }
}

seedSkills();
